language: generic
env: SWIFT_VERSION=5.4

jobs:
  include:
    - os: linux
      dist: xenial
      name: Ubuntu 16.04
    - os: linux
      dist: bionic
      name: Ubuntu 18.04
    - os: linux
      dist: focal
      name: Ubuntu 20.04
    - os: osx
      osx_image: xcode10.1
      name: High Sierra
    - os: osx
      osx_image: xcode11.3
      name: Mojave
    - os: osx
      osx_image: xcode12.2
      name: Catalina
    - os: osx
      osx_image: xcode12.4
      name: Big Sur

install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
  - make
  - make test
